version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: pos-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: E@P4ssw0rd@123
      MYSQL_DATABASE: pos
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pos-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    ports:
      - "127.0.0.1:${PMA_PORT}:80"

  web:
    image: node:20
    restart: always
    command: npm run start:dev
    working_dir: /mnt
    volumes:
      - ../:/mnt
    depends_on:
      - mysql
    ports:
      - "127.0.0.1:${APP_PORT}:3001"
